### ISSUE TITLE
Modyfing your monkai++ theme

### ISSUE THREAD

**Issue by baconsplit** [DrgOv/dark-palenight#2]
Hello sir,
I know this is the wrong place to contact you but I couldn't find any other way.

I had a quick question about your [monokai++dark](https://github.com/DrgOv/monokai-plusplus) theme for VSCode. I really like the general setup you've greated and it works well for the languages I use. But I wish to swap out some of the colors but just wasn't able to understand the logic behind these themes.

Could you help me out edit the json, where I put color codes or what designer I could use to edit this theme?

Would be really awesome if you can help me out and I can delete this false Issue afterwards!

**Comment by DrgOv** [comment]
Hi,
No worries. Thanks for the kind words. 
The theme was mainly made for personal uses, but if somebody else likes it, fine by me.
 If you want to change things, in the themes folder you have 2 files, 1 json and 1 tmTheme. 
The json file takes priority over the tmTheme one.
I use the tmTheme for syntax highlight and the json for background colors. 
If you want to change something, you can just write it in the json and it should take priority and override anything already set.

**Comment by baconsplit** [comment]
Thank you, this helped me alot. I've been searching for the variables in the json and didnt look into the tmTheme. Got all my changes done in the tmTheme.

Thanks for helping me out and I wish you great holidays!
You can close/delete this ticket as you wish
